#!/usr/bin/env python

import sys
import termbar

if __name__ == "__main__":
    line = sys.stdin.read()
    vals = [("", float(v)) for v in line.split()]
    a = termbar.TermBar(vals, write_axis_labels=True, write_values=True)
    a.draw()
    
